"""setting default attendee count

Revision ID: 6dd88b56c77a
Revises: ace95c007cb2
Create Date: 2026-07-10 14:24:01.739385

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dd88b56c77a"
down_revision: str | Sequence[str] | None = "ace95c007cb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("presentation_sessions", "attendees", existing_type=sa.INTEGER(), nullable=False, server_default="0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("presentation_sessions", "attendees", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
