"""added temporary pubsub event model

Revision ID: 806aad924aea
Revises: 9d153f48988c
Create Date: 2026-08-22 13:52:54.796735

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "806aad924aea"
down_revision: str | Sequence[str] | None = "9d153f48988c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pubsub_events",
        sa.Column("hub", sa.String(), nullable=False),
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pubsub_events")
    # ### end Alembic commands ###
