"""added slide_deck model

Revision ID: 9d153f48988c
Revises: 6dd88b56c77a
Create Date: 2026-07-10 14:28:19.345287

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d153f48988c"
down_revision: str | Sequence[str] | None = "6dd88b56c77a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slide_decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("first_slide_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["first_slide_id"],
            ["slides.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slide_decks")
    # ### end Alembic commands ###
