"""adding presentation session

Revision ID: 9e3adb2827eb
Revises: e4bf38fbf0a4
Create Date: 2026-03-31 10:42:04.102952

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e3adb2827eb"
down_revision: str | Sequence[str] | None = "e4bf38fbf0a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "presentation_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("current_slide_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_slide_id"],
            ["slides.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("presentation_sessions")
    # ### end Alembic commands ###
