"""changing vote client_id to audience_id

Revision ID: ace95c007cb2
Revises: 3fc6828fcca2
Create Date: 2026-03-31 18:09:04.152630

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ace95c007cb2"
down_revision: str | Sequence[str] | None = "3fc6828fcca2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("presentation_sessions", sa.Column("attendees", sa.Integer(), server_default="0"))
    op.add_column("votes", sa.Column("audience_id", sa.String(), nullable=False))
    op.drop_column("votes", "client_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("votes", sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("votes", "audience_id")
    op.drop_column("presentation_sessions", "attendees")
    # ### end Alembic commands ###
